### ISSUE TITLE
Black formatting?

### ISSUE THREAD

**Issue by KalobTaulien** [wagtail/wagtail.io#20]
Not an issue, but more of a discussion point. 

What are everyones thoughts on using **Black** to format Python files? I'm working on a couple updates to this repo and thought to myself, "While I'm working on specific files, I could format them as a separate commit."

**Comment by kaedroho** [comment]
Hey Kalob, I'm in favour of this!

**Comment by thibaudcolas** [comment]
I think people at Torchbox are beyond debating this – we just use it on all (new) projects at this stage. @KalobTaulien if you’re keen to add this to wagtail.io I think it would be very welcome, but since that PR would be likely to cause lots of merge conflicts I would suggest you identify someone to review it beforehand to make sure this spends the least amount of time possible un-merged.
